### ISSUE TITLE
Fix YUI compression (redux)

### ISSUE THREAD

**Issue by plroebuck** [vercel/ms#112]
According to Mocha's changelog, PR #53 didn't finish the job.

mochajs/mocha#1035
> This wasn't fully fixed. Having `options.long` still causes YUI to fail.

```js
-  return options.long ? fmtLong(val) : fmtShort(val);
+  return options['long'] ? fmtLong(val) : fmtShort(val);
```

**Comment by leerob** [comment]
Closing as stale and lack of traction, please comment back if this is still an issue.
