### ISSUE TITLE
Unexpected behavior when parsing a human-readable expression

### ISSUE THREAD

**Issue by osher** [vercel/ms#115]
## Use-Case Overview

I added `ms` to let Ops configure some intervals on their `~/config/local.yaml` in a human-readable fashion.

The ops tried:
```
app:
   interval: 1h 30min
```
This evidently did not behave as expected.

## Reproduction steps:
```
const ms = require('ms');
const v = ms('1h 30min')
console.log(v)
```
## expected behavior
```
5400000
```
## found behavior
```
undefined
```

**Comment by osher** [comment]
Workaround: 
parse every part by yourself, and sum the elements

```
const s = '1h 30min';
const v = s.replace(/([0-9])[ \t]+([^ \t])/g, (_, digit, char) => `${digit}${char}`)
      .trim().split(/[ \t]+/)
      .map(val => parse(val)).reduce((a,b) => a + b);
```

**Comment by styfle** [comment]
`ms('1h') + ms('30m')` is the best workaround.

Colons are probably better like this feature request #24
