### ISSUE TITLE
Add a /docs folder to do documentation on this package.

### ISSUE THREAD

**Issue by NotMoni** [vercel/ms#128]
We need a /docs folder. I want to add documentation to all the use-cases and just give a detailed understanding on this npm pkg.

**Comment by NotMoni** [comment]
If you guys approve, I can start working on documentation on my own fork and then submit a pr.

**Comment by leerob** [comment]
Hello! We're planning on keeping docs inside the README, but I'm willing to review a PR adding additional docs if there's something missing. If so, would you mind opening an issue for the docs you want to add specifically? Thanks 🙏
