### ISSUE TITLE
Doesn't support more then 24 days?

### ISSUE THREAD

**Issue by RFlintstone** [vercel/ms#129]
I added `ms` into my Discord bot but `ms` seems to only support up to 24 days otherwhise it will set the timer automaticly to 0. Is this a bug from the current build? (I installed the latest npm build)

**Example Code:** 
```
const ms = require("ms"); 
```
```
setTimeout(async function(){
     console.log("Timer finished")
}, ms(mutetime));
```
(I set the time/value for `ms` with a discord command - this works as it should with for example 10s or 7d however would I like to be able to do 1y or maybe -1 so it will never stop)

**Comment by MatthiasKunnen** [comment]
No bugs in this package:
```js
const ms = require("ms")
console.log(ms('23 days')); // 1987200000
console.log(ms('24 days')); // 2073600000
console.log(ms('25 days')); // 2160000000
```

What is happening is that you're overflowing a 32-bit signed integer which can contain a maximum of 2,147,483,647 ms (about 24.8 days).

See <https://nodejs.org/api/timers.html#timers_settimeout_callback_delay_args>.

> When delay is larger than 2147483647 or less than 1, the delay will be set to 1. Non-integer delays are truncated to an integer.

**Comment by MatthiasKunnen** [comment]
You could use [long-timeout](https://www.npmjs.com/package/long-timeout) if you want intervals or timeouts greater than 24 days.
