### ISSUE TITLE
Should ms handle 9h30 and 3m50s ?

### ISSUE THREAD

**Issue by 1000i100** [vercel/ms#138]
#55, #102, #25 was pull request for that, #54, #24, #110 are open issues for that.

the pull request have been closed without merging, and the issues are still opened.

Is there a lack of something in the pull request, and i shoud write one with all quality test requered for the pull request to be merged ?
Or shoud the issues #54, #24, #110 should be closed with the `wontfix` flag ? (and an other project like https://github.com/Cat66000/ms-i18n/issues/2 should implement it ? )

**Comment by styfle** [comment]
It says the reason here: https://github.com/vercel/ms/pull/55#issuecomment-276677287
