### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ImBoing** [vercel/ms#145]
Hello I was curious if you could so stuff like `1m5s` to ms

**Comment by yahu1031** [comment]
Hello @boingfromdiscord, you would probably read the [README.md's convert-from-milliseconds](https://github.com/vercel/ms#convert-from-milliseconds). Anyhow you can write it as `ms(65000)`.

Regards

**Comment by styfle** [comment]
No but you can do `ms('1m') + ms('5s')` to achieve the same result.
