### ISSUE TITLE
hi i have issue with ms.

### ISSUE THREAD

**Issue by SusenkaOREOcze** [vercel/ms#146]
i am having problem with ms, iam making bot and i doing permission and when i am trying to execute the command console says

  throw new Error(
  ^

Error: val is not a non-empty string or a valid number. val=undefined

and it showing thsi piece of code:
```
module.exports = function(val, options) {
  options = options || {};
  var type = typeof val;
  if (type === 'string' && val.length > 0) {
    return parse(val);
  } else if (type === 'number' && isFinite(val)) {
    return options.long ? fmtLong(val) : fmtShort(val);
  }
  throw new Error(
    'val is not a non-empty string or a valid number. val=' +
      JSON.stringify(val)
  );
};
```

i dont know what to do...
can someone help please ????

**Comment by ethamitc** [comment]
You're going to have to show **your** code, not the code where the error is throwing. We need to see what you're doing wrong to correct it.

**Comment by SusenkaOREOcze** [comment]
i remaked my code now its okay
