### ISSUE TITLE
regular expression feature

### ISSUE THREAD

**Issue by Yevhen-Molchaniuk** [vercel/ms#158]
Please add export of string regular expression
https://github.com/vercel/ms/blob/1c6264b795492e8fdecbc82cb8802fcfbfc08d26/index.js#L53

**Comment by Xample** [comment]
An alternate would be to [type the method in typescript](https://www.typescriptlang.org/play?#code/C4TwDgpgBAzglgcwHZQLxQOQFoNQD4AFGGAUKJFAK5JzBqYAmuejAhiDM5gBZcbcB7SgCdO+HqL4BbaXAA2cuDAgBjAUgZiWGKXCRbMupJWAQDO81OUrzt1es19r5gO58XECAGtzIPiAhWSXEMEGDtDABuMnBoZTAg1mABYXpcDDxiaPJoYDgpCAAxFKkk+gADABIAb3hkAF8a4ykAIwhhRtqIBOEklM7qWnry6JIAM2oVPPUoKwAKPIKALkWikqSASiWoZrbU6pIoKGEIYBEUADlWC8ioAHo748C5KHywOQgCpGAkuBmYQSUOQMKBtKDAbjtCCAMgISPUSCR5hgAExQBjsTgbI4PKAARgA7MiABwABjJZMRMDmGFxTCxRwZOKJADYACzkilI3Ek3j0xmPADMzI5nKpKIAdABWKDcSRYnEAThFJMp1ORvIZ-KghJFqppMj5WuF5L1ksxmuxj0lJq5fkNlqgAtxksl+ONNrF3JJGHtOK9eqwArRGJ990eWGRkoVyN1SKwuI1mpxgfdoupEbJoa1GZVevawhSPtuOL0ADdWIoQas9bioCoIN9KEE7cXHkgBLBKGAwCk6GMUlAAkEgA):

I've no idea of the official supported pattern

**Comment by leerob** [comment]
^ We now have those types!

https://github.com/vercel/ms#typescript-support
