### ISSUE TITLE
ESM version

### ISSUE THREAD

**Issue by MatthiasKunnen** [vercel/ms#159]
Currently, `ms` is written in CommonJS. This has some drawbacks:

- They cannot be treeshaken properly resulting in larger bundles [<sup>[1]</sup>](https://web.dev/commonjs-larger-bundles/)
- It requires `esModuleInterop` for TypeScript [<sup>[2]</sup>](https://github.com/vercel/ms/issues/127)
- They are not in the ECMAScript spec as opposed to ESModules [<sup>[3]</sup>](https://tc39.es/ecma262/#sec-modules)[<sup>[4]</sup>](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive) for which support is being built into browsers[<sup>[4]</sup>](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive) and Node[<sup>[5]</sup>](https://nodejs.org/api/esm.html)

What I propose is to use the [`main`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main) and [`module`](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md) field in `package.json` to provide both ESM and CommonJS. This change is fully backwards compatible and can be achieved by using TypeScript, Webpack, or Rollup. I'd propose to go the TypeScript way which has the added benefit of type safety and allows `ms` to bundle types. 

If you would accept this I could make a PR.

**Comment by Divlo** [comment]
Great suggestion!:+1:

I would suggest that we rewrite the package in TypeScript, so we can include types declarations builtin and deprecate `@types/ms`.
