### ISSUE TITLE
Cannot find module 'ms' or its corresponding type declarations. (3.0.0-canary.0)

### ISSUE THREAD

**Issue by crashmax-dev** [vercel/ms#165]
`dist` folder is missing

![image](https://user-images.githubusercontent.com/15673111/133447565-4776c3e3-9446-4af2-9b71-c6904c602b4d.png)

**Comment by oceanroleplay** [comment]
@leerob please release the package again with dist folder.

**Comment by leerob** [comment]
Yeah, it appears our build script isn't working properly just yet. Thanks for reporting! We will get this fixed.

**Comment by mrmckeb** [comment]
This was my fault sorry, the last commit to #163 wasn't tested correctly.

This resolves it - https://github.com/vercel/ms/pull/166

**Comment by leerob** [comment]
Released! Let us know if it's working for you.

https://github.com/vercel/ms/releases/tag/3.0.0-canary.1
