### ISSUE TITLE
TypeError: (0 , ms_1.default) is not a function

### ISSUE THREAD

**Issue by awesomelike** [vercel/ms#186]
I am receiving an error in a Typescript project:
`TypeError: (0 , ms_1.default) is not a function`

Is this a known issue, and how can this be resolved?

**Comment by drackp2m** [comment]
Could you explain to me how you solved the problem @awesomelike?

I'm trying to use it in a node project with Typescript (NestJS) and I have the same problem. 🥹

**Comment by drackp2m** [comment]
In my case I didn't have the `ms` dependency in my `package.json` (although I did in my node_modules).

Running this:

`yarn add ms`
`yarn add --dev @types/ms`

and adding `"esModuleInterop": true` to `compilerOptions` of `tsconfig.json` works for me.

**Comment by TREER00T** [comment]
> In my case I didn't have the `ms` dependency in my `package.json` (although I did in my node_modules).
> 
> Running this:
> 
> `yarn add ms` `yarn add --dev @types/ms`
> 
> and adding `"esModuleInterop": true` to `compilerOptions` of `tsconfig.json` works for me.

Thank you

**Comment by sajjadmrx** [comment]
> In my case I didn't have the `ms` dependency in my `package.json` (although I did in my node_modules).
> 
> Running this:
> 
> `yarn add ms` `yarn add --dev @types/ms`
> 
> and adding `"esModuleInterop": true` to `compilerOptions` of `tsconfig.json` works for me.

🙏

**Comment by tirzasrwn** [comment]
for me i use
```ts
const ms = require('ms');
```
instead of 
```ts
import ms from 'ms';
```
it works for me, but idk why

**Comment by itsmunim** [comment]
> for me i use
> 
> const ms = require('ms');
> instead of
> 
> import ms from 'ms';
> it works for me, but idk why

This is what worked for me, weird!
