### ISSUE TITLE
How to use ms with French

### ISSUE THREAD

**Issue by nozyx12** [vercel/ms#208]
Hello !
I actually create a French discord bot, i create a mute command but i can't convert my string of French (example: 1j = 1d or 1 jour = 1 day)

Please help me

**Comment by thib3113** [comment]
the easier solution can maybe to convert your string before passing it to ms ?

convert jour => day, and j => d .

**Comment by obumnwabude** [comment]
Or what will it take to internationalize the package to some extent?

**Comment by dudeman9801** [comment]
I can take this up. What other languages should I add other than French?

**Comment by nozyx12** [comment]
I think you can most speak languages like French, Spanish and others...

**Comment by nozyx12** [comment]
Thank you for all your responses, have a nice day!
