### ISSUE TITLE
Is the project still being maintained?

### ISSUE THREAD

**Issue by timi137137** [vercel/ms#209]
I've found that this package is practically unusable for Typescript.
Not because the function is unavailable, but because the type definition is missing and invalid.
For example: 

![image](https://github.com/vercel/ms/assets/36812439/d8e382d3-4b21-4518-8be8-75899f483cd0)

I can contribute to this package if needed, this package is very important for too many scenarios.
Looking forward to reply!

Environment:
"ms": "^3.0.0-canary.1",
"@types/ms": "^0.7.34",

**Comment by timi137137** [comment]
Add new example:
![image](https://github.com/vercel/ms/assets/36812439/56dc2c9f-da3b-415f-a052-94817ae431df)
Normally, the IDE automatically prompts for type completion import, but this package does not

**Comment by TooTallNate** [comment]
`ms@3.0.0-canary.1` contains its own type definitions. You don't need to use `@types/ms`.

**Comment by timi137137** [comment]
> `ms@3.0.0-canary.1` contains its own type definitions. You don't need to use `@types/ms`.

IDE said he couldn't detect it
