### ISSUE TITLE
ms('1y') or ms('1 year') is returning a value slightly off an actual year

### ISSUE THREAD

**Issue by ignxdank** [vercel/ms#215]
ms('1 year') returns 31557600000, when a year is actually 31556952000. This is causing my timestamps (Date.now() + ms('1 year')) to be about 5 hours off, does anyone know why ms is returning this value and how I can fix it?

**Comment by vserpokryl** [comment]
@ignxdank ms is simple library to convert human-readable string to milliseconds
For 1 a developer must take into account the leap year
31557600000 - 365.25 days
31556952000 - 365.2425 days
And that's it
A developer should take into account that the number of milliseconds in a year and month is not constant, but it is constant for a second, minute, hour, day, week. These are the ones that need to be used when counting in critical parts
